# Generated by Django 5.2.1 on 2025-06-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userservicebooking_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservicebooking',
            name='address',
            field=models.CharField(default='address_name', max_length=255),
        ),
    ]
