# Generated by Django 5.2.3 on 2025-06-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_servicebooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='assigned',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
